# Spring JPA H2 data store (in memory by default)
spring:
    datasource:
        driverClassName: org.h2.Driver
        username: sa
        password: password
        url: jdbc:h2:mem:testdb
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
logging:
    config: classpath:log4j2.yml
